# Generated by Django 5.2.7 on 2025-10-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tripadvisor_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant"),
                            ("hotel", "Hôtel"),
                            ("monument", "Monument"),
                            ("museum", "Musée"),
                            ("park", "Parc"),
                            ("entertainment", "Divertissement"),
                            ("shopping", "Shopping"),
                            ("nightlife", "Vie Nocturne"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "price_level",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "$"), (2, "$$"), (3, "$$$"), (4, "$$$$")],
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("num_reviews", models.IntegerField(default=0)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("opening_hours", models.JSONField(blank=True, null=True)),
                ("photo_url", models.URLField(blank=True)),
                ("photo_count", models.IntegerField(default=0)),
                ("awards", models.JSONField(blank=True, default=list)),
                ("cuisine_types", models.JSONField(blank=True, default=list)),
                ("hotel_class", models.IntegerField(blank=True, null=True)),
                ("hotel_style", models.JSONField(blank=True, default=list)),
                ("likes_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "attractions",
                "ordering": ["-likes_count", "-rating"],
                "indexes": [
                    models.Index(
                        fields=["country", "city"],
                        name="attractions_country_e545bd_idx",
                    ),
                    models.Index(
                        fields=["category"], name="attractions_categor_b26c08_idx"
                    ),
                    models.Index(
                        fields=["-likes_count"], name="attractions_likes_c_9e6dcc_idx"
                    ),
                ],
            },
        ),
    ]
