# Generated by Django 5.2.7 on 2025-10-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="category",
            field=models.CharField(
                choices=[
                    ("restaurants", "Restaurants"),
                    ("hotels", "Hôtels"),
                    ("attractions", "Attractions"),
                    ("geos", "Sites Géographiques"),
                ],
                max_length=50,
            ),
        ),
    ]
