# Generated by Django 5.2.7 on 2025-10-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=255, unique=True)),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("tourist", "Touriste"),
                            ("professional", "Professionnel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
    ]
