# Generated by Django 5.2.7 on 2025-10-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="capital",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
