# Generated by Django 5.2.7 on 2025-10-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_capital"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="capital",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
