# Generated by Django 5.2.7 on 2025-10-29 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attractions", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compilation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Ma compilation", max_length=255)),
                (
                    "sort_by",
                    models.CharField(
                        choices=[
                            ("budget_asc", "Budget croissant"),
                            ("budget_desc", "Budget décroissant"),
                            ("distance", "Distance optimale"),
                        ],
                        default="distance",
                        max_length=20,
                    ),
                ),
                (
                    "total_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compilations",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "compilations",
            },
        ),
        migrations.CreateModel(
            name="CompilationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attractions.attraction",
                    ),
                ),
                (
                    "compilation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="compilations.compilation",
                    ),
                ),
            ],
            options={
                "db_table": "compilation_items",
                "ordering": ["order"],
                "unique_together": {("compilation", "attraction")},
            },
        ),
    ]
